### ISSUE TITLE
On full screen, the clock disappear

### ISSUE THREAD

**Issue by Jsmilegithub** [Kolcha/DigitalClock5#1]
When I enter full screen mode, the clock disappear, despite the mode "Staying on top on other windows is on".
![image](https://github.com/user-attachments/assets/9315eaff-75cc-4d99-9382-d6fdcc8a0899)
![image](https://github.com/user-attachments/assets/4d5b91bb-242a-4443-9ff7-82cccdde0325)

**Comment by Kolcha** [comment]
this is intended. clock removes "stay on top" flag when it detects fullscreen window. I can add an option to keep it above fullscreen windows, but this will not work reliably. details below.

regardless of MS documentation (at least from ~2016) which says that there are no such thing as "fullscreen windows" at all, fullscreen windows really exist and they are special - they have some undocumented flags set and who knows how system treats them. even more, most of the fullscreen windows are DirectX-based (like players or games), such things require special tricks (like interception of DirectX calls, what a lot of gamer's software do) to draw something on them, so in general case any regular app can't appear above such windows by the nature. but, since win 10 something has changed, it is known that my old clock is able to appear above many (but not all) common players.

anything related to web browsers is even worse... almost always, there is an invisible fullscreen window (also with very unusual flags set) for unknown purposes (but it is definitely created by Chromium engine). how  player is rendered is unknown to me, but definitely this is some kind of hack.

just to summarize, if I add option, it will not work for all the cases because of the nature of fullscreen windows. this is expected, it even should not work for players at all, the fact that it works is a bug as for me, but the roots of this are in Windows itself, and I'm not interested in finding what exactly happens as I'm not a windows developer, even not an active windows user.
