### ISSUE TITLE
openSUSE Tumbleweed: не виден значок в системном лотке панели KDE.

### ISSUE THREAD

**Issue by aaly11** [Kolcha/DigitalClock5#11]
[![Не виден значок в системном лотке.](https://paste.opensuse.org/pastes/aae7bc52329e/raw)](https://paste.opensuse.org/pastes/59c2abfb80c5/raw)
[Проект пакета DigitalClock5 на OBS.](https://build.opensuse.org/package/show/home:AndnoVember:LXQt:Qt6/DigitalClock5)
До последнего времени только отсутствие значка в системном трее доставляло неудобство.
Не в первый раз сталкиваюсь со ["значком невидимкой"](https://github.com/ddanilov/soundscape/issues/4).
А теперь ещё прибавилась [ошибка сборки пакета версии 5.0.4](https://build.opensuse.org/public/build/home:AndnoVember:LXQt:Qt6/openSUSE_Tumbleweed/x86_64/DigitalClock5/_log).

**Comment by Kolcha** [comment]
во первых, линукс официально не поддерживается, т.к. часы просто бесполезны на Wayland - они просто [неперемещаемые](https://stackoverflow.com/questions/67318357/how-to-set-the-position-of-a-wayland-window-on-the-screen) и это фича by design. за Wayland все же будущее как ни крути, а изобретать какие хаки специфичные для каждого окружения и "надеятся что оно будет работать" я не собираюсь, хватит мне и хаков вокруг "поверх всех окон" на винде... и корень проблемы там также не мой...

как показало прошлое, пользователей моего проекта под линуксом крайне немного (ожидаемо - не та среда), поэтому в силу ограничений окружения решил больше не поддерживать.

насчет "значка-невидимки", это давно известная "фича" KDE (и только KDE). они своими плагинами начиная с некоторого времени (еще где-то 2020й а то и ранее) сделали с Qt прям что-то невероятное - если использовать svg файл (а не просто имя из темы) в качестве значка, то значок в трее не рисуется. если png - то все ок, но png уже никто давно не использует. проявляется только при сборке с Qt из системы, с кастомным Qt (допустим офф инсталлер) все работает, т.к. KDE-шные плагины не загружаются.

в свое время я явно раскопал "корень зла" и сделал [хак в кастомном icon engine](https://github.com/Kolcha/DigitalClock4/blob/master/paletteicon/palette_icon_engine.cpp#L117) который использовали старые часы в том числе для трея, но в новых он не используется, там вообще значок рисуется руками в самом прямом смысле слова, видимо и в этом случае работает та же логика что и с svg... хака в этой логике рисовки нету (и не факт что можно добавить или что оно будет работать).

а что не собирается, это ожидаемо - я перешел к [использованию платформенных API](https://github.com/Kolcha/DigitalClock5/commit/7442199b8247fbf01163620d85805b90ffee08b6) чтобы хоть как-то смягчить извечную проблему с "поверх всех окон", и имлементации под линукс у меня попросту нету, отсюда и undefined reference.

почему такое решение - используя Qt API я так и не смог заставить нормально работать (тем более на всех платформах) изменение этих разных флажков "на лету", а пользователи сразу начали жаловаться что без перезапуска программы не применяется (да и самому неудобно). такие вещи как изменение разных флажков в "стиле" окна обычно требует видимого окна (по крайней мере в документации WinAPI раньше такое видел, и оно действительно обычно не работает если окно невидимое), но Qt делает что-то невероятное для этого простого вызова, и в результате окно обычно исчезает, притом в большинстве случаев "с концами" (и поведение зависит от того что меняешь и на какой платформе).

в старых часах на этот счет также был хак который приходилось экспериментально "подганять" от версии к версии. то что там осталось не факт что работает нормально даже с последним Qt 5.15, а с Qt 6 так вообще не работает. изменение флагов окна это явно не то что должно требовать "некий велосипед", особенно если знаешь как оно может (да и было и должно) быть при использовании системных API. это одна из самых простых вещей что легко можно сделать с использованием системных API, и то что работает безотказно (по крайней мере раньше было, ныне увы уже нет - на винде это только вопрос времени когда окно "свалится", и проблем за ээтим тут несколько).

так что предлагаю просто забить на сборку под линукс и все.

у этого проекта и так нету будущего, а тем более под линуксом. возможно я его вообще "с корнями" удалю в скором времени. он и так появился из-за очень паршивого психологического состояния... просто очень много писать мне помогало... в результате меньше чем за 2 недели появилась полноценная программа на создание которой "в обычном режиме" понадобилось бы месяца 3 а то и более... и "выбрасывать" было жалко, вот и опубликовал.

**Comment by Kolcha** [comment]
возможно к следующим выходным я выпущу еще одну версию (или просто перезалью 5.0.4), попробую втащить некоторые хаки со старой и по крайней мере пофиксить сборку под линуксом, но как написал выше, под линуксом будущего нет

**Comment by Kolcha** [comment]
5.0.4 перезалита, сборка на линуксе исправлена, значок также исправлен

**Comment by aaly11** [comment]
Спасибо за исправления. Теперь значок на своём месте и даже стрелки в нём следуют за временем.
Но всегда ли идёт всё как планировалось? Так появляется лишняя кнопка окна в **области задач** панели KDE, с которой можно успешно справиться, настроив "Особые параметры окна для DigitalClock5" ([Arrangement & Access] **_Skip taskbar_** - Force - Yes).

**Comment by Kolcha** [comment]
раньше я использовал очень агрессивный флаг (что-то типа BypassWindowManager), вероятнее всего именно он и убирал кнопку, но как показала практика, ныне его использование приводит к исчезновению окна (по крайней мере в моем окружении - KDE на Wayland на ArchLinux), даже если часы запускать с xcb (X11 backend, чтобы можно было хотябы перемещать). возможно поведение в других дистрах или окружениях будет другим, но в любом случае его явно лучше больше не использовать (до вчерашнего вечера я даже не пробовал запускать часы на линуксе, поэтому даже не знал что там да как, код был просто перетащен со старых часов).

хак с "типом окна" позволяющий убрать кнопку с "пуска" на винде также применим и к линуксу, но увы у него также есть side effect - при потере фокуса окно также исчезает (также зависит от окружения), поэтому я его также не использую. если решить проблему можно какими настройками KDE - это лучший вариант (я далеко не знаток возможностей KDE, у меня от него только панелька в стиле "старого GNOME 2" и все, да и вообще я использую его только из-за отсутствия другой альтернативы: GNOME по определению "не катит" еще где-то с 2015-го, а остальное обычно "не дружит" с HighDPI экраном или "просто некие поделки", ну или не хватает кастомизации чтобы придать "вид панельки старого GNOME").

в любом случае поддерживать линукс я не собираюсь, и вообще удивлен что кто-то решил собрать пакет из этого добра... да и еще при условии что система сборки (да и код тоже) вообще к этому не годится... но мелочи типа проблем сборки обычно пофиксить очень просто.
