### ISSUE TITLE
Task tray icon always 1 hour wrong

### ISSUE THREAD

**Issue by SanderBouwhuis** [Kolcha/DigitalClock5#13]
I love the fact that the tray icon has the actual time as an icon.
Unfortunately, it's always 1 hour off.

I am realizing now that it could be because of DST (daylight saving time).
Could you please fix it?

**Comment by Kolcha** [comment]
tray icon displays local time (uses system time zone) regardless of any clock settings. logic behind just asks system current time, it has nothing to do with DST (everything is behind the call I'm using).

I can't reproduce the issue unless I change time zone in clock settings to something else (what has difference with my local time).

maybe it just looks odd, but it behaves as classical analog clock - hour hand moves a little every minute (e.g. at 3:30 hour hand will be between 3 and 4, not pointing to 3), not only when hour changes. this may look "1 hour off" if it gets closer to the next hour (let's say 3:45, just following my example, in this case hour hand is very close to 4, rather than 3).

tray icon is too small to be "accurate enough" and even not supposed to be so, it was implemented just for fun.

**Comment by SanderBouwhuis** [comment]
Yeah, you are right.
Maybe you could change it so that it only shows the hour. That way, you have an easier way to determine how late it is approximately. Currently, it is very difficult to tell the hour and minute dials apart.
