### ISSUE TITLE
How to keep display when i press win+D

### ISSUE THREAD

**Issue by emma160310** [Kolcha/DigitalClock5#3]
When I press win+D to return to the desktop, the clock will not be displayed. I have to right-click a blank area on the desktop to display it again. I hope to set it so that it is displayed on the desktop even after using win+D. And I don't want to be pinned all the time.

**Comment by Kolcha** [comment]
clock is just a regular window like many other apps, so Win+D causes it to be minimized. it is strange that it can appear again just by clicking in empty area... maybe because of some trick to hide app icon from taskbar...

in DigitalClock 4 I had some hack to "survive" Win+D, but I'm not sure where it is implemented :) and if it still works and is relevant. I'll try to do something around it, but this will be unreliable solution very likely.
