### ISSUE TITLE
Customize the size of the background

### ISSUE THREAD

**Issue by o000u** [Kolcha/DigitalClock5#5]
Hi Nick! Me again ^_^ ...

Today, I was pleasantly surprised to find that DC5 has reached version 5.0.2!And what surprised me even more was that you have implemented the function of "clock and background color following system theme"!It works perfectly!
For me, 5.0.2 is already practical enough!Thank you for your excellent work!!
Additionally, there is a small issue: currently, the clock background size is the same as the clock, which makes the clock look less conspicuous. Can we make the background slightly larger than the clock? Allow the clock to have a certain distance from the background border.or...add an option for users to customize the size of the background?

Cheers! @Kolcha

**Comment by Kolcha** [comment]
Hi!

yes, I added option to follow the system theme, as it was quite easy to add (even surprisingly many files have to be changed https://github.com/Kolcha/DigitalClock5/commit/1bc9e2a109fc50ba1e478c71149562ef8ecbca4e)... maybe I'll reconsider its implementation later.

what about spacing, all extra spacing was removed here https://github.com/Kolcha/DigitalClock5/commit/dfa7726f377722047dde914d4d360cb31eb8ef6e intentionally. I plan to add options to configure different aspects of spacing (including "background expansion") with the next version as not only you reported inconvenience with spacing, so this became my primary focus.

but next release will happen not so soon as it was previously, very likely only at the end of month. I'm too busy at work (and as result too tired) nowadays, so clock is "postponed" a bit. previous 2 versions had been released so quickly just because significant issues were reported. so, please wait.

**Comment by o000u** [comment]
OK,OK,as always, look forward to it!

**Comment by o000u** [comment]
Today I upgraded to 5.0.3, it's perfect! Excellent work! cheers！！^_*  @Kolcha
